name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive

    - name: Build contracts
      run: make all-via-docker

    - name: Run tests for secp256r1_blake160 rust
      run: cargo test
      working-directory: ./tests/secp256r1_blake160

    - name: Set up ckb-debugger
      run: make install

    - name: run secp256r1 bench
      run: make run-secp256r1-bench
